# Generated by Django 5.1.1 on 2024-10-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver_request',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
