# Generated by Django 5.1.1 on 2024-10-31 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_receiver_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver_request',
            name='DonerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.doner'),
        ),
    ]
