# Generated by Django 5.1.1 on 2024-11-02 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_receiver_request_donername'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('replay', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.receiver')),
            ],
        ),
    ]
