# Generated by Django 5.1.1 on 2024-11-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_doner_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
